### ISSUE TITLE
Porting from absolute references to relative references in GeoNode

### ISSUE THREAD

**Issue by EddyCatt** [geosolutions-it/oaw-geonode#43]
OAW is now setting up a proxy (https://hgis.woldan.oeaw.ac.at/ )
While doing it, they've figured out that a few references are still absolute and linking to http://woldan3.arz.oeaw.ac.at
They're asking if, and eventually how, all absolute references can be changed to relative ones.

**Comment by lpasquali** [comment]
@EddyCatt @randomorder 
In order to generate a doc to handle these changes I re-analyzed the situation of occurrences of woldan2 or woldan3 server anywhere, from filesystem to database, here is result of analisys:


To respond to the customer question the shjort answer is no, it is not possible to have relative URLs, 
because django uses the SITEURL variable to generate most of the html with "static URLs", so we need to 
configure the service for the final URL.

Changes needed to .env

These three values should be updated like this in order to make the final URL working with correct references:
```
ALLOWED_HOSTS=['django','woldan3.arz.oeaw.ac.at', 'woldan2.arz.oeaw.ac.at', 'hgis.woldan.oeaw.ac.at']
SITEURL=https://hgis.woldan.oeaw.ac.at/
GEOSERVER_PUBLIC_LOCATION=https://hgis.woldan.oeaw.ac.at/geoserver/
```

changing SITEURL should let django generate "most of pages" with correct URL.

This analysis below covers what is left out from the previous sentence "most of the pages". 

GeoStories (just two references which can be changed by hand for thumbnails)

I think that changing two occurrences in the Django admin page should be quicker than running any geonode management command for this:

1) login as admin
2) Click on admin button 
3) Click on Admin on the cascading menu
4) Click on GeoApps -> Geo Apps
5) there are 3 geostories:
- 562	Eisenbahn Österreich Ungarn	
- 501	Ostindien-Expedition 1595
- 116 GeoStory DEMO (to be skipped)
6) Change thumbnail URL both for geostory with id 562 and id 501


Database references to woldan2

```
select * from search_columns('woldan2.arz.oeaw.ac.at');
 schemaname |  tablename  | columnname | rowctid 
------------+-------------+------------+---------
 public     | django_site | domain     | (0,4)
 public     | django_site | name       | (0,4)

oaw_geonode=# select * from django_site;
 id |         domain         |          name          
----+------------------------+------------------------
  1 | woldan2.arz.oeaw.ac.at | woldan2.arz.oeaw.ac.at
(1 row)

oaw_geonode=# 
```
This most likely affects generation of title html tag, which still points to the dev site, and should be changed.
 
Question for GeoNode developers: These fields were not updated by any restore procedure, should we update the value by hand? 
Also these values are updated when changing SITEURL, is this generally correct?


Database references to woldan3

for db they are only in monitoring_requestevent (lots) and just one reference in monitoring_host. 
This is actually correct, because it does not interfere on relative front-end URLS, I do not think we need to do anything here.

Example:
```
oaw_geonode=# select * from monitoring_host;
 id |          name          |     ip     | active 
----+------------------------+------------+--------
  3 | woldan3.arz.oeaw.ac.at | 10.3.6.43  | t
  4 | geoserver              | 172.18.0.5 | t
(2 rows)

oaw_geonode=#
```

GeoServer datadir references to woldan2

There are none.

GeoServer datadir references for woldan3

OAuth2 ublic URLs should be changed by hand in datadir editing the file below (restart of GeoServer is needed):
```
./security/filter/geonode-oauth2/config.xml:  <accessTokenUri>http://woldan3.arz.oeaw.ac.at/o/token/</accessTokenUri>
./security/filter/geonode-oauth2/config.xml:  <userAuthorizationUri>http://woldan3.arz.oeaw.ac.at/o/authorize/</userAuthorizationUri>
./security/filter/geonode-oauth2/config.xml:  <redirectUri>http://woldan3.arz.oeaw.ac.at/geoserver/index.html</redirectUri>
./security/filter/geonode-oauth2/config.xml:  <checkTokenEndpointUrl>http://woldan3.arz.oeaw.ac.at/api/o/v4/tokeninfo/</checkTokenEndpointUrl>
./security/filter/geonode-oauth2/config.xml:  <logoutUri>http://woldan3.arz.oeaw.ac.at/account/logout/</logoutUri>
```
the Proxy Base URL should be updated, because it reflects the public GeoServer URL we update in the first step into GeoNode's `.env`
```
./global.xml:    <proxyBaseUrl>http://woldan3.arz.oeaw.ac.at/geoserver</proxyBaseUrl>
```

under the ./workspaces/geonode/ directory in the GeoServer datadir all coverages.xml and featuretype.xml configuration files for datastores 
and layers are pointing to http://woldan3.arz.oeaw.ac.at, and they should be updated to the new URL.

Question, the URLs are in the form:
- http://woldan3.arz.oeaw.ac.at/catalogue/csw/<stuff>
- http://woldan3.arz.oeaw.ac.at/showmetadata/xsl/<stuff>

is there a geonode command to update them to the correct SITEURL?

**Comment by lpasquali** [comment]
@randomorder Yes I think is totally possible, I will make it a document

**Comment by lpasquali** [comment]
@randomorder @EddyCatt https://docs.google.com/document/d/1M4oUpHH7GLV3fpnb2usWL1l_bMu_nlRoYUwpUrCjhGg/edit#heading=h.14lgxd727gkx
